# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agents.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61gents.proto\x12\x06\x61gents\x1a\x1bgoogle/protobuf/empty.proto\"\xc2\x01\n\x0bLedgerEntry\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x10\n\x08sigprint\x18\x04 \x01(\t\x12\x11\n\tcoherence\x18\x05 \x01(\x02\x12\x33\n\x08\x66\x65\x61tures\x18\x06 \x03(\x0b\x32!.agents.LedgerEntry.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xac\x01\n\x0eSigprintUpdate\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x10\n\x08sigprint\x18\x02 \x01(\t\x12\x11\n\tcoherence\x18\x03 \x01(\x02\x12\x36\n\x08\x66\x65\x61tures\x18\x04 \x03(\x0b\x32$.agents.SigprintUpdate.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"6\n\x0bGardenEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32V\n\x0fSigprintService\x12\x43\n\x11GetLatestSigprint\x12\x16.google.protobuf.Empty\x1a\x16.agents.SigprintUpdate2@\n\rLedgerService\x12/\n\x0b\x43ommitEntry\x12\x13.agents.LedgerEntry\x1a\x0b.agents.Ack2@\n\rGardenService\x12/\n\x0bNotifyEvent\x12\x13.agents.GardenEvent\x1a\x0b.agents.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEDGERENTRY_FEATURESENTRY']._loaded_options = None
  _globals['_LEDGERENTRY_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_SIGPRINTUPDATE_FEATURESENTRY']._loaded_options = None
  _globals['_SIGPRINTUPDATE_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_LEDGERENTRY']._serialized_start=54
  _globals['_LEDGERENTRY']._serialized_end=248
  _globals['_LEDGERENTRY_FEATURESENTRY']._serialized_start=201
  _globals['_LEDGERENTRY_FEATURESENTRY']._serialized_end=248
  _globals['_SIGPRINTUPDATE']._serialized_start=251
  _globals['_SIGPRINTUPDATE']._serialized_end=423
  _globals['_SIGPRINTUPDATE_FEATURESENTRY']._serialized_start=201
  _globals['_SIGPRINTUPDATE_FEATURESENTRY']._serialized_end=248
  _globals['_GARDENEVENT']._serialized_start=425
  _globals['_GARDENEVENT']._serialized_end=479
  _globals['_ACK']._serialized_start=481
  _globals['_ACK']._serialized_end=503
  _globals['_SIGPRINTSERVICE']._serialized_start=505
  _globals['_SIGPRINTSERVICE']._serialized_end=591
  _globals['_LEDGERSERVICE']._serialized_start=593
  _globals['_LEDGERSERVICE']._serialized_end=657
  _globals['_GARDENSERVICE']._serialized_start=659
  _globals['_GARDENSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
