// Auto-generated by Kira codegen on 2025-10-18T12:31:00.924529+00:00
export interface WorkspaceKnowledge {
  name: string;
  memoryCount: number;
  layerBreakdown: Record<string, number>;
  latestMemory?: string | null;
  ledgerCount: number;
  latestLedger?: {
    ts?: string | null;
    kind?: string | null;
  } | null;
  gardenStage?: string | null;
  echoMode?: string | null;
}

export interface KiraKnowledgeSnapshot {
  generatedAt: string;
  workspaces: WorkspaceKnowledge[];
}
